"""Injection-guard incident log and per-rep alert state

Revision ID: 9b7b659d2338
Revises: 9c7e98deef3b
Create Date: 2026-07-17 16:43:46.299401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b7b659d2338'
down_revision: Union[str, Sequence[str], None] = '9c7e98deef3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injection_incidents',
    sa.Column('incident_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rep_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('row_ref', sa.String(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.rep_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index('ix_injection_incidents_rep_occurred', 'injection_incidents', ['rep_id', 'occurred_at'], unique=False)
    op.create_table('rep_injection_alert_state',
    sa.Column('rep_id', sa.UUID(), nullable=False),
    sa.Column('tripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_incident_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.rep_id'], ),
    sa.PrimaryKeyConstraint('rep_id')
    )
    op.add_column('reps', sa.Column('injection_alerts_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reps', 'injection_alerts_enabled')
    op.drop_table('rep_injection_alert_state')
    op.drop_index('ix_injection_incidents_rep_occurred', table_name='injection_incidents')
    op.drop_table('injection_incidents')
    # ### end Alembic commands ###
