"""contact history and approval gate

Revision ID: badeb3a5a860
Revises: 
Create Date: 2026-07-09 22:25:33.966696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badeb3a5a860'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('lead_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('primary_phone', sa.String(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('contact_history',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('call', 'text', 'email', 'slack_handoff', 'sheet_edit', name='channel'), nullable=False),
    sa.Column('tool', sa.Enum('initiate_lead_call', 'send_lead_text', 'send_lead_email', 'dispatch_slack_handoff', 'update_lead_sheet', name='tool'), nullable=False),
    sa.Column('stage', sa.Enum('drafted', 'awaiting_rep_approval', 'approved', 'executed', 'rejected', 'expired', name='stage'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rep_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.Enum('delivered', 'failed', 'pending', 'answered', 'no_answer', 'voicemail', 'didnt_call', name='outcome'), nullable=True),
    sa.Column('content_ref', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_contact_history_lead_id', 'contact_history', ['lead_id'], unique=False)
    op.create_index('ix_contact_history_timestamp', 'contact_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_history_timestamp', table_name='contact_history')
    op.drop_index('ix_contact_history_lead_id', table_name='contact_history')
    op.drop_table('contact_history')
    op.drop_table('leads')
    # ### end Alembic commands ###
