"""add rep_google_credentials table

Revision ID: d2caf87d6b35
Revises: e7b9516164cf
Create Date: 2026-07-12 12:37:12.571279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2caf87d6b35'
down_revision: Union[str, Sequence[str], None] = 'e7b9516164cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rep_google_credentials',
    sa.Column('rep_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=False),
    sa.Column('granted_file_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.rep_id'], ),
    sa.PrimaryKeyConstraint('rep_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rep_google_credentials')
    # ### end Alembic commands ###
