"""reps and sessions, rep_id fk on contact_history

Revision ID: e7b9516164cf
Revises: f8a997ea2f0a
Create Date: 2026-07-09 23:49:15.734888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b9516164cf'
down_revision: Union[str, Sequence[str], None] = 'f8a997ea2f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reps',
    sa.Column('rep_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rep_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rep_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('rep_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.rep_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.alter_column('contact_history', 'rep_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='rep_id::uuid')
    op.create_foreign_key(None, 'contact_history', 'reps', ['rep_id'], ['rep_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_history', type_='foreignkey')
    op.alter_column('contact_history', 'rep_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('rep_sessions')
    op.drop_table('reps')
    # ### end Alembic commands ###
