"""dedup mapping and run locks

Revision ID: f8a997ea2f0a
Revises: badeb3a5a860
Create Date: 2026-07-09 22:39:21.919992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8a997ea2f0a'
down_revision: Union[str, Sequence[str], None] = 'badeb3a5a860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_locks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_action_locks',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('last_action_committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('lead_source_rows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('row_ref', sa.String(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'row_ref', name='uq_lead_source_row')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_source_rows')
    op.drop_table('lead_action_locks')
    op.drop_table('agent_run_locks')
    # ### end Alembic commands ###
